# Generated by Django 3.2.3 on 2021-05-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productcount_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcount',
            name='productname',
        ),
    ]
